apiVersion: batch/v1
kind: Job
metadata:
  name: gw-rag-cad-original-cpu
  labels: 
    eidf/user: s2523062-infk8s
  annotations: 
      eidf/email: s2523062@ed.ac.uk
      eidf/user: s2523062-infk8s
spec:
  backoffLimit: 0
  template:
    metadata:
        labels: 
          eidf/user: s2523062-infk8s
        annotations: 
            eidf/email: s2523062@ed.ac.uk
            eidf/user: s2523062-infk8s
    spec:
      restartPolicy: Never
      containers:
      - name: pytorch-con
        image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
        command: ["/bin/sh","-c"]
        args:
        - |
          apt update -y --fix-missing;
          apt install -y git;
          sleep infinity;
        volumeMounts:
        - mountPath: /mnt/ceph_rbd
          name: volume
        resources:
          requests:
            cpu: 8
            memory: "80Gi"
          limits:
            cpu: 8
            memory: "80Gi"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: gw-pv
